<?php
/**
 * Created by PhpStorm.
 * User: DELL
 * Date: 2019/5/6
 * Time: 22:32
 * Email: 574482856@qq.com
 */

defined('APP_PATH') OR exit('No direct script access allowed');

class EntityModel extends BaseModel {

  public function _init() {
    parent::_init(); // TODO: Change the autogenerated stub
    /**
     * 连接到小程序数据库
     */
    $this->chooseConnection('wxxcx');
  }
}