<?php
/**
 * Created by PhpStorm.
 * User: DELL
 * Date: 2019/5/6
 * Time: 22:32
 * Email: 574482856@qq.com
 */

defined('APP_PATH') OR exit('No direct script access allowed');

class EntitycolumnModel extends BaseModel {
  public function _init() {
    parent::_init(); // TODO: Change the autogenerated stub
    /**
     * 连接到小程序数据库
     */
    $this->chooseConnection('wxxcx');
  }
  /**
   * 第一次创建的时候，采用批量插入
   * @method saveMulti
   * @param $entityId
   * @param $insertData
   * @return string
   * 2019/5/11 17:16
   */
  public function saveMulti($entityId, $insertData) {

    $data = array_map(function ($val) {
      return $this->autoAddtimeData($val, 'insert');
    }, $insertData);

    if ($insertData || !in_array($insertData))
      return '';

    try {
      $this->startTransaction();

      //清除所有 实体下所有的元素
      $this->query('delete from ' . $this->table . ' where entity_id=?', [$entityId]);

      //创建数据库表
      $entityInfo = $this->entityModel->getOne($entityId, ['id', 'title', 'table_name', 'table_engine', 'commenttxt']);

      //如果表存在，删除
      $this->query('DROP TABLE IF EXISTS `' . $entityInfo['table_name'] . '`;');

      //保存实体属性
      $ids = $this->_db->insertMulti($this->table, $data);
      $this->autoaddtime && debugMessage('未自动补充createtime和updatetime');
      $this->_logSql();

      $sqlCombineData = $this->dataCombine($insertData);
      //重新创建建 表 sql
      $insertSql = $this->getCreateTableSql($entityInfo, $sqlCombineData);

      $this->query($insertSql);

      $this->commit();
      if (!$ids)
        return '';
      else
        return implode(',', $ids);
    } catch (mysqli_sql_exception $exception) {
      $this->rollback();
    } catch (Exception $exception) {
      $this->rollback();
    }
  }

  /**
   * 创建表
   * @method getCreateTableSql
   * @param $entityInfo
   * @param $data
   * @return string
   * 2019/5/11 7:42
   */
  private function getCreateTableSql($entityInfo, $data) {

    if (!$data)
      return '';

    $sqlData = [];
    $sqlData[] = "CREATE TABLE {$entityInfo['table_name']}(";
    $sqlData[] = "`id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '//id',";
    foreach ($data as $key => $attribute) {
      $sqlData[] = $this->parseAttributeSql($attribute) . ",";
    }
    $sqlData[] = "`status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '//状态 -1 删除 0 禁用  1正常',";
    $sqlData[] = "`sort_id` int(11) unsigned DEFAULT '0' COMMENT '排序id',";
    $sqlData[] = "`updatetime` int(11) NOT NULL,";
    $sqlData[] = "`createtime` int(11) NOT NULL DEFAULT '0' COMMENT '//创建时间 时间戳的方式',";
    $sqlData[] = "PRIMARY KEY (`id`)";
    $sqlData[] = ")ENGINE={$entityInfo['table_engine']} AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='{$entityInfo['commenttxt']}';";

    return implode('', $sqlData);
  }


  /**
   * 组合数据,使用用户自定义数据，覆盖attribute属性
   * @method dataCombine
   * @param array $entityList
   * @return array|void
   * 2019/5/11 7:20
   */
  public function dataCombine(array $entityList) {

    if (!$entityList)
      return [];

    $entityList = arrayOrderby($entityList, 'attribute_id', SORT_ASC);

    //从属性列表中获取数据
    $attributeIds = [];
    foreach ($entityList as $key => $val) {
      if (isset($val['attribute_id']))
        $attributeIds[] = $val['attribute_id'];
    }

    $attrbuteList = $this->attributeModel->getAttributeListByIds($attributeIds);
    $attrbuteList = arrayOrderby($attrbuteList, 'id', SORT_ASC);

    //结果按照属性id合并
    $entityList = array_map(function ($v1, $v2) {
      if ($v1['id'] == $v2['attribute_id'])
        return array_merge($v1, $v2);
    }, $attrbuteList, $entityList);

    return $entityList;
  }

  /**
   * 根据属性得到修改属性的sql param
   * @method parseAttributeSql
   * @param $attribute
   * @return string
   * 2019/5/11 12:06
   */
  private function parseAttributeSql($attribute) {

    $data = [];

    $data[] = "`{$attribute['column_name']}`";
    $data[] = "`{$attribute['column_type']}`";

    if (strlen($attribute['column_value']))
      $data[] = '(' . $attribute['column_value'] . ')';

    if ($attribute['notnull'])
      $data[] = 'NOT NULL';

    if ($attribute['column_default'])
      $data[] = "default '{$attribute['column_default']}'";
    else {
      //column_type 1 tinyint 2 int 3 bigint 8 float 9 decimal
      if (in_array($attribute['column_type'], [1, 2, 3, 8, 9])) {
        $data[] = 'default 0';
      } else
        $data[] = "default ''";
    }

    if ($attribute['commenttxt'])
      $data[] = "comment '{$attribute['commenttxt']}'";

    return trim(implode(' ', $data));
  }

  /**
   * 删除元素，均删除数据表中字段
   * @method entityColumnDelete
   * @param $entityId
   * @param $id
   * @return bool|int
   * @throws InvalideException
   * 2019/5/11 15:12
   */
  public function entityColumnDelete($entityId, $id) {

    //删除成功后，需要将表字段同时删除
    try {
      $this->startTransaction();

      $where = [
        getWhereCondition('entity_id', $entityId),
        getWhereCondition('id', $id)
      ];
      $columnAttribute = $this->getOne($where, ['attribute_id']);
      if (!$columnAttribute)
        return FALSE;

      $attributeId = $columnAttribute['attribute_id'];

      $attributeInfo = $this->attributeModel->getOne($attributeId, ['column_name']);

      if (!$attributeInfo)
        return FALSE;


      $entityInfo = $this->entityModel->getOne($entityId, ['table_name']);

      if (!$entityInfo)
        return FALSE;

      if (in_array($attributeInfo['column_name'], $this->getFields())) {
        $dropColumnSql = 'alter table ' . $entityInfo['table_name'] . ' drop column ' . $attributeInfo['column_name'] . ' ;';
        $this->query($dropColumnSql);
      }

      return $this->delete($id);


    } catch (mysqli_sql_exception $exception) {
      debugMessage($exception->getMessage() . ' file:' . $exception->getFile());
      $this->rollback();
    }

  }

  /**
   * 添加单个元素
   * @method addSignone
   * @param $entityId
   * @param $data
   * 2019/5/11 15:23
   */
  public function addSignone($entityId, $data) {

    try {
      $this->startTransaction();

      $entityInfo = $this->entityModel->getOne($entityId, ['table_name']);

      if (!$entityInfo)
        return FALSE;

      $attributeInfo = $this->attributeModel->getAttributeListByIds([$data['attribute_id']]);

      $columnInfo = $this->parseAttributeSql($attributeInfo);

      if (!in_array($attributeInfo['column_name'], $this->getFields())) {
        $addColumnSql = 'alter table ' . $entityInfo['table_name'] . ' add column ' . $columnInfo . ' ;';
        $this->query($addColumnSql);
      }

      $result = $this->insert($data);

      $this->commit();

      return $result;

    } catch (mysqli_sql_exception $exception) {
      debugMessage($exception->getMessage() . ' file:' . $exception->getFile());
      $this->rollback();
    }
  }

}