<?php
/**
 * Created by PhpStorm.
 * User: songyongzhan
 * Date: 2018/12/28
 * Time: 15:54
 * Email: 574482856@qq.com
 *
 * redis操作模型
 */
defined('APP_PATH') OR exit('No direct script access allowed');

class RedisModel extends BaseModel {

  /**
   * @var MyRedis
   */
  public $redis;

  protected function _init() {
    parent::_init(); // TODO: Change the autogenerated stub
    $this->redis = MyRedis::getInstance(
      [
        'ip' => REDIS_HOST,
        'port' => REDIS_PORT,
        'passwd' => REDIS_PASSWORD,
        'prefix' => PREFIX,
        'expire' => REDIS_EXPIRE,
      ]
    );
  }
}
